# Generated by Django 3.1.4 on 2020-12-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Создан', max_length=255, null=True),
        ),
    ]
