# Generated by Django 3.1.4 on 2020-12-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20201217_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
    ]
