# Generated by Django 3.1.4 on 2020-12-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20201218_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='created', max_length=255),
        ),
    ]
