# Generated by Django 3.1.4 on 2020-12-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20201221_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
