# Generated by Django 3.1.4 on 2020-12-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20201226_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
